# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-20 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jake', '0003_auto_20200220_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-upload_date']},
        ),
    ]
