# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-21 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jake', '0006_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
